name: blt_ext
version: 1.1.1
description: Chrome extension for BloomToken
authors: Jace Hensley <jacehensley@gmail.com>
homepage: https://github.com/jacehensley/blt_ext

environment:
  sdk: ^1.24.2

dependencies:
  chrome: ^0.9.33
  over_react: ^1.18.1
  react: ^3.4.3
  transform_sass: ^0.3.1

transformers:
- over_react
- chrome
- transform_sass
- $dart2js:
    csp: true
